const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('nitro', {
  getVersions: () => ipcRenderer.invoke('get-versions'),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  saveSettings: (data) => ipcRenderer.invoke('save-settings', data),
  launchGame: (opts) => ipcRenderer.invoke('launch-game', opts),
  cancelLaunch: () => ipcRenderer.invoke('cancel-launch'),
  getServerStatus: () => ipcRenderer.invoke('get-server-status'),
  getLauncherMeta: () => ipcRenderer.invoke('get-launcher-meta'),
  getOwnerMode: () => ipcRenderer.invoke('get-owner-mode'),
  ownerUnlock: (password) => ipcRenderer.invoke('owner-unlock', password),
  ownerGetLiveConfig: () => ipcRenderer.invoke('owner-get-live-config'),
  ownerSaveLiveConfig: (config) => ipcRenderer.invoke('owner-save-live-config', config),
  ownerGetPublishSettings: () => ipcRenderer.invoke('owner-get-publish-settings'),
  ownerSavePublishSettings: (settings) => ipcRenderer.invoke('owner-save-publish-settings', settings),
  ownerPublishLiveConfig: (opts) => ipcRenderer.invoke('owner-publish-live-config', opts),
  ownerExportLiveConfig: (config) => ipcRenderer.invoke('owner-export-live-config', config),
  getPresets: () => ipcRenderer.invoke('get-presets'),
  applyPreset: (opts) => ipcRenderer.invoke('apply-preset', opts),
  getMicrosoftAccount: () => ipcRenderer.invoke('get-microsoft-account'),
  getAuthSecurity: () => ipcRenderer.invoke('get-auth-security'),
  microsoftLogin: (opts) => ipcRenderer.invoke('microsoft-login', opts),
  microsoftLogout: () => ipcRenderer.invoke('microsoft-logout'),
  repairInstall: () => ipcRenderer.invoke('repair-install'),
  openLaunchLog: () => ipcRenderer.invoke('open-launch-log'),
  readLaunchLog: () => ipcRenderer.invoke('read-launch-log'),
  clearLaunchLog: () => ipcRenderer.invoke('clear-launch-log'),
  pingServer: (host) => ipcRenderer.invoke('ping-server', host),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  copyText: (text) => ipcRenderer.invoke('copy-text', text),
  openMinecraftFolder: () => ipcRenderer.invoke('open-minecraft-folder'),
  openClientFolder: () => ipcRenderer.invoke('open-client-folder'),
  getEnvironment: () => ipcRenderer.invoke('get-environment'),
  setupJava8: () => ipcRenderer.invoke('setup-java8'),
  getServerHub: () => ipcRenderer.invoke('get-server-hub'),
  toggleFavoriteServer: (server) => ipcRenderer.invoke('toggle-favorite-server', server),
  getModToggles: () => ipcRenderer.invoke('get-mod-toggles'),
  setModToggle: (opts) => ipcRenderer.invoke('set-mod-toggle', opts),
  exportSettings: () => ipcRenderer.invoke('export-settings'),
  importSettings: () => ipcRenderer.invoke('import-settings'),
  pickResourcePack: () => ipcRenderer.invoke('pick-resource-pack'),
  applyResourcePack: () => ipcRenderer.invoke('apply-resource-pack'),
  downloadLauncherUpdate: () => ipcRenderer.invoke('download-launcher-update'),
  searchMods: (opts) => ipcRenderer.invoke('modrinth-search', opts),
  installMod: (opts) => ipcRenderer.invoke('modrinth-install', opts),
  listInstalledMods: (opts) => ipcRenderer.invoke('list-installed-mods', opts),
  uninstallMod: (opts) => ipcRenderer.invoke('uninstall-mod', opts),
  openModsFolder: (opts) => ipcRenderer.invoke('open-mods-folder', opts),
  onModInstallProgress: (cb) => ipcRenderer.on('mod-install-progress', (_, payload) => cb(payload)),
  spotifySaveClientId: (clientId) => ipcRenderer.invoke('spotify-save-client-id', clientId),
  spotifyConnect: (opts) => ipcRenderer.invoke('spotify-connect', opts),
  spotifyStatus: () => ipcRenderer.invoke('spotify-status'),
  spotifyDisconnect: () => ipcRenderer.invoke('spotify-disconnect'),
  spotifyPlayback: (opts) => ipcRenderer.invoke('spotify-playback', opts),
  minimize: () => ipcRenderer.invoke('window-minimize'),
  toggleMaximize: () => ipcRenderer.invoke('window-toggle-maximize'),
  close: () => ipcRenderer.invoke('window-close'),
  onLaunchProgress: (cb) => ipcRenderer.on('launch-progress', (_, payload) => cb(payload)),
  onWindowState: (cb) => ipcRenderer.on('window-state', (_, payload) => cb(payload)),
  friendsState: () => ipcRenderer.invoke('friends-state'),
  friendsSearch: (name) => ipcRenderer.invoke('friends-search', name),
  friendsAdd: (name) => ipcRenderer.invoke('friends-add', name),
  friendsAccept: (name) => ipcRenderer.invoke('friends-accept', name),
  friendsDecline: (name) => ipcRenderer.invoke('friends-decline', name),
  friendsRemove: (name) => ipcRenderer.invoke('friends-remove', name),
  friendsSend: (opts) => ipcRenderer.invoke('friends-send', opts),
  friendsOpenChat: (name) => ipcRenderer.invoke('friends-open-chat', name),
  onFriendsUpdated: (cb) => ipcRenderer.on('friends-updated', (_, payload) => cb(payload)),
  skinsState: () => ipcRenderer.invoke('skins-state'),
  skinsAdd: (query) => ipcRenderer.invoke('skins-add', query),
  skinsAddFile: () => ipcRenderer.invoke('skins-add-file'),
  skinsRename: (opts) => ipcRenderer.invoke('skins-rename', opts),
  skinsModel: (opts) => ipcRenderer.invoke('skins-model', opts),
  skinsRemove: (id) => ipcRenderer.invoke('skins-remove', id),
  skinsApply: (id) => ipcRenderer.invoke('skins-apply', id),
  hostingState: () => ipcRenderer.invoke('hosting-state'),
  hostingSelectWorld: (id) => ipcRenderer.invoke('hosting-select-world', id),
  hostingCreateWorld: (opts) => ipcRenderer.invoke('hosting-create-world', opts),
  hostingConfig: (opts) => ipcRenderer.invoke('hosting-config', opts),
  hostingStart: (opts) => ipcRenderer.invoke('hosting-start', opts),
  hostingStop: () => ipcRenderer.invoke('hosting-stop'),
  hostingRefresh: () => ipcRenderer.invoke('hosting-refresh'),
  hostingJoinInfo: () => ipcRenderer.invoke('hosting-join-info'),
  hostingInvite: (name) => ipcRenderer.invoke('hosting-invite', name),
  onHostingUpdated: (cb) => ipcRenderer.on('hosting-updated', (_, payload) => cb(payload))
});
